
server:
  #?????????
  port: 8083
  #?????????????localhost:8083??????????
  servlet:
    context-path: /test1

spring:
  datasource:
    # ???????
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cal?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid???????
    druid:
      # ?????????????
      initial-size: 5
      # ??????????
      min-idle: 5
      # ?????????
      max-active: 20
      # ????????????????
      max-wait: 60000
      # ??????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
      test-while-idle: true
      # ?????????????testWhileIdel?????
      time-between-eviction-runs-millis: 60000
      # ????????????????????????????????????(??????????????)
      min-evictable-idle-time-millis: 30000
      # ??????????????sql ?????????(oracle?? select 1 from dual)
      validation-query: select 'x'
      # ????????validationQuery????????,???????,???true
      test-on-borrow: false
      # ????????validationQuery????????,???????,???true
      test-on-return: false
      # ????preparedStatement, ???PSCache,PSCache???????????????????oracle,?mysql??????
      pool-prepared-statements: false
      # ????????filters????????sql?????stat: ?????Slf4j:?????waLL: ??sqL??
      filters: stat,wall,slf4j
      # ???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
      max-pool-prepared-statement-per-connection-size: -1
      # ????DruidDataSource?????
      use-global-data-source-stat: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl